### ISSUE TITLE
amp-list example not displaying 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/docs#2471] opened 2019-07-11 16:23 UTC
### Current Behavior
Theres an empty space where there should be an example on the [amp-list reference documentation under usage](https://amp.dev/documentation/components/amp-list#usage). 

Please also provide:
- Page link: https://amp.dev/documentation/components/amp-list#usage
- Screenshots: 
- [sample location in AMPHTML Repo](https://snag.gy/3rgk6K.jpg)
- [Lack of sample on amp.dev](https://snag.gy/AdvFH5.jpg)

**Comment by matthiasrohmer** [comment] 2019-07-11 16:31
Duplicate of #2469.

**Closed by matthiasrohmer** 2019-07-11 16:31 UTC
Labels: Category: Documentation, Status: Pending Triage, Type: Bug

**Comment by CrystalOnScript** [comment] 2019-07-11 16:40
haha, back to back - thanks!

**Comment by matthiasrohmer** [comment] 2019-07-11 16:41
You're welcome 😁
