### ISSUE TITLE
amp-bind guide has tiny column for "Functions"

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#698] opened 2017-09-19 01:01 UTC
## Description of the issue:

Load [https://www.ampproject.org/docs/reference/components/amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind) with your browser window large enough to display the sidebar.

Then the "Functions" column header is only 84px wide.  Subtracting 60px of padding leaves only 24px for the word "Functions".  The content of that column is only 20px wide.

Saw this with Chrome 60 on a Mac.

<img width="215" alt="screen shot 2017-09-18 at 9 01 05 pm" src="https://user-images.githubusercontent.com/29419498/30571271-89aa5668-9cb4-11e7-8eb3-49f4ee52e6e1.png">

**Comment by bpaduch** [comment] 2017-09-19 12:18
Duplicate of https://github.com/ampproject/docs/issues/687, which was fixed in last night's build.  Thx!

**Closed by bpaduch** 2017-09-19 12:18 UTC
