### ISSUE TITLE
Publish AMP-native-app integration guide

### ISSUE THREAD

**Issue by cramforce** [ampproject/docs#547] opened 2017-06-09 17:56 UTC
We should publish a guide for how native apps can link out to AMP docs.

**Comment by bpaduch** [comment] 2017-06-09 19:42
Please provide context, use cases, an example.

**Comment by cramforce** [comment] 2017-06-09 19:52
@pbakaus has all of that. Basically we have a doc. We just need to publish it.

**Comment by bpaduch** [comment] 2017-06-14 13:02
Duplicate of #548

**Closed by bpaduch** 2017-06-14 13:02 UTC
Labels: P2: Medium, Type: Doc Update
