### ISSUE TITLE
amp-analytics page is broken

### ISSUE THREAD

**Issue by cathyxz** [ampproject/docs#2498] opened 2019-07-15 22:03 UTC
Per https://github.com/ampproject/amphtml/issues/23324, the page for amp-analytics (https://amp.dev/documentation/components/amp-analytics/) is broken on amp.dev. It's also linked to from the components page. We should either fix the page, or correct the link. =)

**Comment by sebastianbenz** [comment] 2019-07-16 08:02
Duplicate of #2504

**Closed by sebastianbenz** 2019-07-16 08:02 UTC
Labels: Status: Pending Triage, Type: Bug
