### ISSUE TITLE
Documentation for pages like amp-bind difficult to read

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/docs#696] opened 2017-09-18 16:55 UTC
See: https://www.ampproject.org/docs/reference/components/amp-bind and screenshot below.

When one column is too wide, some columns have just enough room for one character per line.

<img width="855" alt="screen shot 2017-09-18 at 09 54 23" src="https://user-images.githubusercontent.com/3888212/30553874-62147190-9c57-11e7-87c8-f1244e519d26.png">

**Comment by bpaduch** [comment] 2017-09-18 17:05
Duplicate of https://github.com/ampproject/docs/issues/687

**Closed by bpaduch** 2017-09-18 17:05 UTC
