### ISSUE TITLE
"Embed & use AMP as a data source", "See it in action" section has mismatching links to example code

### ISSUE THREAD

**Issue by nichtverstehen** [ampproject/docs#765] opened 2017-11-29 17:15 UTC
## Description of the issue found on ampproject.org

- Page link: https://www.ampproject.org/docs/guides/pwa-amp/amp-in-pwa, section "See it in action"
- Description of the documentation issue:
Example app running on https://choumx.github.io/amp-pwa/ is not built from sources at https://github.com/ampproject/amp-publisher-sample/tree/master/amp-pwa as documented.

Instead it is built from https://github.com/choumx/amp-pwa, which is more advanced, with animated page transitions. It is very confusing to search for how those transitions are done and not find any traces of them.

See also https://github.com/ampproject/amp-publisher-sample/issues/84.

## How do we reproduce the issue?

1. Clone and start https://github.com/ampproject/amp-publisher-sample/tree/master/amp-pwa 
2. Observe that this is a different app from https://choumx.github.io/amp-pwa/ that is claimed to run from the same source.

What browser are you using? Chrome
What O/S are you using? OSX

**Comment by bpaduch** [comment] 2018-04-19 18:42
Closing this as it's a duplicate of https://github.com/ampproject/amp-publisher-sample/issues/84.

**Closed by bpaduch** 2018-04-19 18:42 UTC
Labels: P2: Medium
