### ISSUE TITLE
Bug in ServiceWorker precache

### ISSUE THREAD

**Issue by jridgewell** [ampproject/docs#1016] opened 2018-06-28 20:34 UTC
## Description of the issue found on ampproject.org

Seeing the following error on https://www.ampproject.org/

```
Uncaught bad-revisioned-cache-list: The 'precache()' method expectsan array of revisioned urls like so: ['/example/hello.1234.txt', {path: 'hello.txt', revision: '1234'}]
createError @ workbox.js:20
precache @ workbox.js:149
(anonymous) @ service-worker.js?v2:8
```

## How do we reproduce the issue?

1. Go to https://www.ampproject.org/
2. Open Browser Inspector
3. Refresh
4. Wait for error

What browser are you using?
Chrome 67

What O/S are you using?
OS X 10.13.3

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36`

**Comment by bpaduch** [comment] 2018-07-16 11:54
Duplicate of #906

**Closed by bpaduch** 2018-07-16 11:54 UTC
