### ISSUE TITLE
All analytics vendors listed

### ISSUE THREAD

**Issue by Christosap** [ampproject/docs#220] opened 2016-10-05 03:59 UTC
Similar to ad vendors page

**Comment by bpaduch** [comment] 2016-11-11 19:25
The analytics vendors are listed on the amp-analytics page: https://www.ampproject.org/docs/reference/components/amp-analytics#analytics-vendors

Does that resolve this issue?

**Comment by Christosap** [comment] 2016-11-11 20:45
This is about this page: https://www.ampproject.org/learn/who/

Some of the entries there are not linked

**Comment by bpaduch** [comment] 2017-02-06 21:15
Duplicate of #243

**Closed by bpaduch** 2017-02-06 21:15 UTC
