### ISSUE TITLE
"FLEX_ITEM" is not described in the online doc

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/docs#142] opened 2016-07-19 21:07 UTC
Copied from @klemy202 's original bug: https://github.com/ampproject/amphtml/issues/4102
cc' @Meggin 

**Short description of your issue**

On the page of amp-img.md we can find a FLEX_ITEM in the list of Supported Layouts, but It is not described in the online documentation.

**How do we reproduce the issue?**

Read the doc!

**What browsers are affected?**

All browsers (I guess!).

**Which AMP version is affected?**

Current website version, that is 1468521759997.

**Comment by bpaduch** [comment] 2016-09-16 15:57
Need to be documented in https://www.ampproject.org/docs/guides/responsive/control_layout.html

**Comment by bpaduch** [comment] 2016-10-03 17:49
Duplicate of https://github.com/ampproject/amphtml/issues/4102; Fixed.

**Closed by bpaduch** 2016-10-03 17:49 UTC
Labels: Section: Learn, Type: Enhancement
