### ISSUE TITLE
jekyll error in pages_toc.html

### ISSUE THREAD

**Issue by Gregable** [ampproject/docs#31] opened 2016-02-05 19:25 UTC
Running `jekyll serve` as per the [README](https://github.com/ampproject/docs/blob/master/README.md), I'm encountering:
```
Liquid Exception: undefined method `sort' for nil:NilClass in _includes/pages_toc.html, included in _get_started/create_page.md
jekyll 2.5.3 | Error:  undefined method `sort' for nil:NilClass
```

**Comment by pbakaus** [comment] 2016-02-05 20:08
Mh, cannot reproduce your issue. Make sure you're running Jekyll 3+ though. Let me know if upgrading helps.

**Comment by Meggin** [comment] 2016-02-22 20:33
I'm not getting this error either, and I've got the latest docs and am re-running it over and over again.

**Comment by Meggin** [comment] 2016-04-26 17:33
Can we close this? Greg, can you try and re-produce?

**Comment by pbakaus** [comment] 2016-07-12 02:49
Closing due to inactivity, and the fact we're not using Jekyll any longer (see megamerge branch).

**Closed by pbakaus** 2016-07-12 02:49 UTC
